playlists:
  - url: "https://www.youtube.com/@NBA/videos"
    tag: "NBA"
    pattern:
      regex: |
        NBA's\s*Top\s*\d+\s*Plays\s*Of\s*The\s*Night
      flags: IGNORECASE
  - url: "https://www.youtube.com/@FIBA3x3/videos"
    tag: "FIBA3x3"
    pattern:
      regex: |
        top\s*\d+|highlights
      flags: IGNORECASE
