name: Get new videos

on:
    workflow_dispatch:
    schedule:
        - cron: "00 8 * * *"

permissions:
  contents: write

env:
  NBA_CHAT_ID: ${{ secrets.NBA_CHAT_ID }}
  NBA_TOKEN: ${{ secrets.NBA_TOKEN }}

jobs:
    scheduled:
        runs-on: ubuntu-latest
        steps:
            - name: Check out this repo
              uses: actions/checkout@v3
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: Install package
              run: |-
                  pip install . pre-commit
            - name: Run top-plays
              run: top-plays
            - name: Commit and push if changed
              run: |-
                  pre-commit run check-json --all-files
                  git config user.name "Automated"
                  git config user.email "actions@users.noreply.github.com"
                  git add -A
                  timestamp=$(date --rfc-3339=seconds --utc)
                  git commit -m "Latest data: ${timestamp}" || exit 0
                  git push
